import { formatBasisPointsPercent, formatCurrency, formatStockQuantity, formatWeight } from "@carnicerias/business-logic";
import Link from "next/link";

import { SectionHeader, StatusBadge } from "./admin-ui";

interface AlertRow { productId: string; productName: string; unitType: "WEIGHT" | "UNIT"; current: number; suggested: number; rank: number; label: string }
interface ProductRow { name: string; grams: number; cents: number }
/** Rentabilidad comercial del período (antes de gastos). `null` = el usuario no puede verla o no se pudo calcular. */
export interface BranchProfitability { grossProfitCents: number; grossMarginBps: number | null; missingCostItems: number; missingCostSales: number; missingCostRevenueCents: number }

export function BranchSummary({ branchId, metrics, change, periodLabel, comparisonLabel, alerts, stockCounts, products, profit }: { branchId: string; metrics: { grossCents: number; kilograms: number; units: number; salesCount: number; averageTicketCents: number }; change: number | null; periodLabel: string; comparisonLabel: string; alerts: AlertRow[]; stockCounts: { out: number; low: number; normal: number }; products: ProductRow[]; profit: BranchProfitability | null }) {
  const metric = (label: string, value: string, detail?: string, note?: string) => <article className="rounded-xl bg-white px-4 py-3 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-stone-500">{label}</p><p className="mt-1 text-2xl font-black text-stone-900">{value}</p>{detail ? <p className={`mt-1 text-sm font-bold ${change !== null && change < 0 ? "text-red-700" : "text-emerald-700"}`}>{detail}</p> : null}{note ? <p className="mt-1 text-xs text-stone-500">{note}</p> : null}</article>;
  return <>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metric(`Ventas ${periodLabel}`, formatCurrency(BigInt(metrics.grossCents)), change === null ? undefined : `${change < 0 ? "↓" : "↑"} ${Math.abs(change).toFixed(1)}% vs ${comparisonLabel}`)}{metric("Kg vendidos", formatWeight(Math.round(metrics.kilograms * 1000)))}{metric("Tickets", String(metrics.salesCount))}{metric("Ticket promedio", formatCurrency(BigInt(metrics.averageTicketCents)))}</section>
    {metrics.units > 0 || profit ? <section className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metrics.units > 0 ? metric("Unidades vendidas", new Intl.NumberFormat("es-AR").format(metrics.units)) : null}{profit ? <>{metric("Ganancia bruta", formatCurrency(BigInt(profit.grossProfitCents)), undefined, "Antes de gastos operativos")}{metric("Margen bruto", profit.grossMarginBps === null ? "—" : `${formatBasisPointsPercent(profit.grossMarginBps)} %`, undefined, "Sobre ventas con costo conocido")}{profit.missingCostItems > 0 ? <p className="self-center text-sm font-bold text-amber-700 sm:col-span-2 lg:col-span-1" role="status">⚠ {profit.missingCostItems === 1 ? "1 línea" : `${String(profit.missingCostItems)} líneas`} sin costo conocido ({formatCurrency(BigInt(profit.missingCostRevenueCents))} vendidos, fuera de la ganancia)</p> : null}</> : null}</section> : null}
    <div className="mt-6 grid gap-7 lg:grid-cols-[1.1fr_.9fr]"><section><SectionHeader title="Requiere atención" action={<Link className="text-sm font-bold text-rose-800 hover:underline" href={`/admin/attention?branch=${branchId}`}>Ver todo →</Link>} /><div className="mt-3 divide-y divide-stone-100 rounded-xl bg-white shadow-sm">{alerts.slice(0, 5).map((row) => <div className="flex items-start justify-between gap-4 px-4 py-3" key={row.productId}><div><strong>{row.productName}</strong>{row.current <= 0 ? <><p className="mt-1 text-sm font-bold text-red-700">Sin stock</p>{row.current < 0 ? <p className="text-sm text-red-700">Faltante: {formatStockQuantity(Math.abs(row.current), row.unitType)}</p> : null}</> : <p className="mt-1 text-sm text-stone-700">Actual: {formatStockQuantity(row.current, row.unitType)}</p>}<p className="mt-1 text-sm font-bold text-teal-700">Reponer: {formatStockQuantity(row.suggested, row.unitType)}</p></div><StatusBadge tone={row.rank === 0 ? "critical" : "warning"}>{row.label}</StatusBadge></div>)}{!alerts.length ? <p className="px-4 py-5 text-emerald-700">Sin alertas de stock.</p> : null}</div></section><section><SectionHeader title="Resumen de stock" /><dl className="mt-3 grid grid-cols-3 gap-3">{[["Agotados", stockCounts.out], ["Bajo mínimo", stockCounts.low], ["Normal", stockCounts.normal]].map(([label, value]) => <div className="rounded-xl bg-white px-4 py-3 shadow-sm" key={label}><dt className="text-xs font-bold uppercase text-stone-500">{label}</dt><dd className="mt-1 text-2xl font-black text-stone-900">{value}</dd></div>)}</dl><SectionHeader title="Productos más vendidos" description="Últimos 7 días" /><div className="mt-3 divide-y divide-stone-100 rounded-xl bg-white shadow-sm">{products.slice(0, 4).map((product) => <div className="flex justify-between gap-3 px-4 py-3" key={product.name}><span className="font-bold">{product.name}</span><span className="text-stone-700">{formatWeight(product.grams)} · <strong>{formatCurrency(BigInt(product.cents))}</strong></span></div>)}{!products.length ? <p className="px-4 py-5 text-stone-500">Sin ventas recientes.</p> : null}</div></section></div>
  </>;
}
