"use client";

import { useActionState, useEffect, useState } from "react";
import { saveCashDiscountAction, type PricingSettingsState } from "../app/admin/actions";

export function PricingSettingsModal({ cashDiscountBps, affectedProducts, skippedProducts }: { cashDiscountBps: number; affectedProducts: number; skippedProducts: number }) {
  const [open,setOpen]=useState(false); const [state,action,pending]=useActionState(saveCashDiscountAction,{} as PricingSettingsState);
  useEffect(()=>{if(state.successToken)setOpen(false);},[state.successToken]);
  return <><button className="rounded-lg border border-stone-300 px-4 py-2.5 text-sm font-bold" onClick={()=>setOpen(true)} type="button">Configuración de precios</button>{open?<div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/30 p-4"><section aria-modal="true" className="w-full max-w-lg rounded-xl bg-white p-5 shadow-xl" role="dialog"><h2 className="text-xl font-black">Configuración de precios</h2><p className="mt-4 text-sm font-bold">DESCUENTO EN EFECTIVO</p><form action={action} className="mt-3 grid gap-4"><label className="grid gap-1 text-sm">Porcentaje<input className="rounded-lg border px-3 py-2" defaultValue={cashDiscountBps/100} max="99.99" min="0" name="cash_discount" required step="0.01" type="number" /></label><p className="text-sm text-stone-600">Se utiliza para calcular el precio de lista de manera que, después del descuento en efectivo, se respete la ganancia objetivo configurada.</p><p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Este cambio modifica el precio de lista calculado de {affectedProducts} productos. {skippedProducts} productos sin costo/ganancia conservarán su precio actual.</p>{state.error?<p className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{state.error}</p>:null}<div className="flex justify-end gap-2"><button className="px-4 py-2 text-sm font-bold" disabled={pending} onClick={()=>setOpen(false)} type="button">Cancelar</button><button className="rounded-lg bg-rose-800 px-4 py-2 text-sm font-bold text-white" disabled={pending}>{pending?"Aplicando…":"Confirmar y aplicar"}</button></div></form></section></div>:null}</>;
}
