import { Modal } from "../../../components/modal";
import { StatusBadge } from "../../../components/admin-ui";
import { requireAdminContext } from "../../../lib/admin";
import { createClient } from "../../../lib/supabase/server";
import { saveAnnouncementAction } from "../actions";

interface Announcement { id: string; branch_id: string | null; title: string; message: string; type: string; priority: number; active: boolean; starts_at: string; ends_at: string | null }
interface AnnouncementClient { from: (table: string) => { select: (columns: string) => { eq: (column: string, value: string) => { order: (column: string, options?: { ascending?: boolean }) => Promise<{ data: Announcement[] | null; error: { message: string } | null }> } } } }
const input = "rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm";
export default async function AnnouncementsPage() {
  const context = await requireAdminContext(); const supabase = await createClient(); const commercial = supabase as unknown as AnnouncementClient;
  const [branchesResult, announcementsResult] = await Promise.all([supabase.from("branches").select("id, name").eq("organization_id", context.organizationId).eq("active", true).order("name"), commercial.from("announcements").select("id, branch_id, title, message, type, priority, active, starts_at, ends_at").eq("organization_id", context.organizationId).order("starts_at", { ascending: false })]);
  const error = [branchesResult.error, announcementsResult.error].find(Boolean); const branches = branchesResult.data ?? []; const branchNames = new Map(branches.map((branch) => [branch.id, branch.name]));
  return <main className="mx-auto max-w-6xl p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-stone-500">Inicio / Avisos</p><h1 className="mt-1 text-3xl font-black tracking-tight">Avisos</h1><p className="mt-2 text-stone-600">Comunicaciones visibles en las sucursales.</p></div><Modal title="Nuevo aviso" trigger="+ Nuevo aviso"><form action={saveAnnouncementAction} className="grid gap-3"><select className={input} name="branch_id"><option value="">Todas las sucursales</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><input className={input} name="title" placeholder="Título" required /><textarea className={input} name="message" placeholder="Mensaje" required rows={4} /><div className="grid gap-3 sm:grid-cols-2"><select className={input} name="type"><option>INFO</option><option>WARNING</option><option>PROMOTION</option><option>STOCK</option><option>INTERNAL</option></select><input className={input} defaultValue="0" max="3" min="0" name="priority" type="number" /></div><input name="active" type="hidden" value="on" /><input name="starts_at" type="hidden" value="" /><input name="ends_at" type="hidden" value="" /><button className="justify-self-start rounded-lg bg-rose-800 px-4 py-2 text-sm font-bold text-white">Publicar aviso</button></form></Modal></div>{error ? <p className="mt-5 rounded-lg bg-red-50 p-4 text-red-800">{error.message}</p> : null}
    <section className="mt-7 divide-y rounded-xl bg-white shadow-sm">{(announcementsResult.data ?? []).map((announcement) => <article className="flex flex-wrap items-start justify-between gap-4 p-4" key={announcement.id}><div><h2 className="font-bold">{announcement.title}</h2><p className="mt-1 text-sm text-stone-600">{announcement.message}</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-stone-500">{announcement.branch_id ? branchNames.get(announcement.branch_id) : "Todas las sucursales"} · {announcement.type}</p></div><StatusBadge tone={announcement.active ? "success" : "neutral"}>{announcement.active ? "Activo" : "Inactivo"}</StatusBadge></article>)}{!announcementsResult.data?.length ? <p className="p-8 text-center text-stone-500">Todavía no hay avisos.</p> : null}</section>
  </main>;
}
