import { formatWeight } from "@carnicerias/business-logic";

import { requireAdminContext } from "../../../lib/admin";
import { createClient } from "../../../lib/supabase/server";
import { recordAdjustmentAction, recordPurchaseAction, recordWasteAction, setStockPolicyAction } from "../actions";

const input = "rounded-lg border border-stone-300 bg-white px-3 py-2";
const reasonLabels: Record<string, string> = { DISCARD: "Descarte", EXPIRY: "Vencimiento", TRIMMING: "Recorte", DETERIORATION: "Deterioro", INVENTORY_DIFFERENCE: "Diferencia de inventario", OTHER: "Otro" };
const operationLabels: Record<string, string> = { PURCHASE: "Compra", WASTE: "Merma", ADJUSTMENT: "Ajuste" };

export default async function StockPage() {
  const context = await requireAdminContext();
  const supabase = await createClient();
  const [stockResult, branchesResult, productsResult, operationsResult, itemsResult, profilesResult] = await Promise.all([
    supabase.from("branch_stock_status").select("*").eq("organization_id", context.organizationId).order("branch_name").order("product_name"),
    supabase.from("branches").select("id, name").eq("organization_id", context.organizationId).eq("active", true).order("name"),
    supabase.from("products").select("id, name, sku").eq("organization_id", context.organizationId).eq("active", true).eq("unit_type", "WEIGHT").order("name"),
    supabase.from("stock_operations").select("id, branch_id, operation_type, supplier, waste_reason, note, occurred_at, actor_profile_id").eq("organization_id", context.organizationId).order("occurred_at", { ascending: false }).limit(50),
    supabase.from("stock_operation_items").select("operation_id, product_id, quantity_grams, system_quantity_before_grams, physical_quantity_grams").eq("organization_id", context.organizationId).order("created_at"),
    supabase.from("profiles").select("id, display_name")
  ]);
  const error = [stockResult.error, branchesResult.error, productsResult.error, operationsResult.error, itemsResult.error, profilesResult.error].find(Boolean);
  const branches = branchesResult.data ?? [];
  const products = productsResult.data ?? [];
  const productNames = new Map(products.map((item) => [item.id, item.name]));
  const branchNames = new Map(branches.map((item) => [item.id, item.name]));
  const profileNames = new Map((profilesResult.data ?? []).map((item) => [item.id, item.display_name]));

  return <main className="mx-auto max-w-7xl p-5 sm:p-10">
    <p className="text-sm font-bold uppercase tracking-wider text-rose-800">Inventario</p><h1 className="mt-1 text-3xl font-black">Stock por sucursal</h1><p className="mt-2 text-stone-600">El actual se deriva del ledger. Las compras, mermas y ajustes agregan movimientos auditados.</p>
    {error ? <p className="mt-5 rounded-lg bg-red-50 p-4 text-red-800">{error.message}</p> : null}
    <section className="mt-7 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-stone-50"><tr><th className="p-3">Sucursal</th><th className="p-3">Producto</th><th className="p-3">Actual</th><th className="p-3">Mínimo</th><th className="p-3">Objetivo</th><th className="p-3">Sugerido</th><th className="p-3">Estado</th></tr></thead><tbody>{(stockResult.data ?? []).map((row) => <tr className="border-t" key={`${row.branch_id ?? "branch"}-${row.product_id ?? "product"}`}><td className="p-3">{row.branch_name}</td><td className="p-3 font-bold">{row.product_name}</td><td className="p-3">{formatWeight(row.current_stock_grams ?? 0)}</td><td className="p-3">{formatWeight(row.minimum_stock_grams ?? 0)}</td><td className="p-3">{formatWeight(row.target_stock_grams ?? 0)}</td><td className="p-3">{formatWeight(row.suggested_replenishment_grams ?? 0)}</td><td className={`p-3 font-black ${row.stock_status === "CRITICAL" ? "text-red-700" : row.stock_status === "LOW" ? "text-amber-700" : "text-emerald-700"}`}>{row.stock_status === "CRITICAL" ? "CRÍTICO" : row.stock_status === "LOW" ? "BAJO" : "NORMAL"}</td></tr>)}</tbody></table></div></section>

    <div className="mt-7 grid gap-6 lg:grid-cols-2">
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Mínimo y objetivo</h2><form action={setStockPolicyAction} className="mt-4 grid gap-3">
        <select className={input} name="branch_id" required><option value="">Sucursal</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={input} name="product_id" required><option value="">Producto</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm">Mínimo kg<input className={input} min="0" name="minimum_kg" required step="0.001" type="number" /></label><label className="grid gap-1 text-sm">Objetivo kg<input className={input} min="0" name="target_kg" required step="0.001" type="number" /></label></div><button className="rounded-lg bg-rose-800 px-4 py-2 font-bold text-white">Guardar política</button>
      </form></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Compra / recepción</h2><p className="mt-1 text-sm text-stone-600">Completá uno o varios productos.</p><form action={recordPurchaseAction} className="mt-4 grid gap-3"><select className={input} name="branch_id" required><option value="">Sucursal</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={input} name="supplier" placeholder="Proveedor (opcional)" />
        <div className="max-h-64 space-y-2 overflow-y-auto rounded-xl border p-3">{products.map((product) => <label className="grid grid-cols-[1fr_9rem] items-center gap-3 text-sm" key={product.id}><input name="product_id" type="hidden" value={product.id} /><span>{product.name}</span><input className={input} min="0" name={`quantity_${product.id}`} placeholder="kg" step="0.001" type="number" /></label>)}</div><input className={input} name="note" placeholder="Nota / remito (opcional)" /><button className="rounded-lg bg-rose-800 px-4 py-2 font-bold text-white">Registrar recepción</button>
      </form></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Merma</h2><form action={recordWasteAction} className="mt-4 grid gap-3"><select className={input} name="branch_id" required><option value="">Sucursal</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={input} name="product_id" required><option value="">Producto</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={input} min="0.001" name="quantity_kg" placeholder="Cantidad kg" required step="0.001" type="number" /><select className={input} name="waste_reason" required>{Object.entries(reasonLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input className={input} name="note" placeholder="Observación" /><button className="rounded-lg bg-rose-800 px-4 py-2 font-bold text-white">Registrar merma</button></form></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Inventario físico / ajuste</h2><p className="mt-1 text-sm text-stone-600">Ingresá el conteo físico; PostgreSQL calcula la diferencia contra el sistema.</p><form action={recordAdjustmentAction} className="mt-4 grid gap-3"><select className={input} name="branch_id" required><option value="">Sucursal</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={input} name="product_id" required><option value="">Producto</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={input} min="0" name="physical_kg" placeholder="Stock físico kg" required step="0.001" type="number" /><input className={input} name="note" placeholder="Motivo / observación" required /><button className="rounded-lg bg-rose-800 px-4 py-2 font-bold text-white">Registrar ajuste</button></form></section>
    </div>

    <section className="mt-7 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Historial de operaciones</h2><div className="mt-4 space-y-3">{(operationsResult.data ?? []).map((operation) => { const operationItems = (itemsResult.data ?? []).filter((item) => item.operation_id === operation.id); return <article className="rounded-xl border p-4" key={operation.id}><div className="flex flex-wrap justify-between gap-3"><div><strong>{operationLabels[operation.operation_type]}</strong> · {branchNames.get(operation.branch_id)}<p className="text-sm text-stone-500">{new Date(operation.occurred_at).toLocaleString("es-AR", { timeZone: context.timezone })} · {profileNames.get(operation.actor_profile_id) ?? operation.actor_profile_id.slice(0, 8)}</p></div><span>{operation.supplier ?? (operation.waste_reason ? reasonLabels[operation.waste_reason] : operation.note)}</span></div><ul className="mt-3 grid gap-2 sm:grid-cols-2">{operationItems.map((item) => <li className="rounded-lg bg-stone-50 p-2 text-sm" key={`${item.operation_id}-${item.product_id}`}>{productNames.get(item.product_id)}: <strong>{item.quantity_grams > 0 ? "+" : ""}{formatWeight(item.quantity_grams)}</strong>{item.physical_quantity_grams !== null ? ` · físico ${formatWeight(item.physical_quantity_grams)}` : ""}</li>)}</ul></article>; })}{!operationsResult.data?.length ? <p className="text-stone-500">Sin operaciones manuales todavía.</p> : null}</div></section>
  </main>;
}
