import { Modal } from "../../../components/modal";
import { StatusBadge } from "../../../components/admin-ui";
import { requireAdminContext } from "../../../lib/admin";
import { createClient } from "../../../lib/supabase/server";
import { saveWeightDiscountAction } from "../actions";

interface Discount { id: string; product_id: string; branch_id: string | null; minimum_grams: number; discount_type: "PERCENTAGE" | "FIXED_PRICE_PER_KG"; discount_value: number; active: boolean; valid_from: string; valid_until: string | null }
interface CommercialClient { from: (table: string) => { select: (columns: string) => { eq: (column: string, value: string) => { order: (column: string, options?: { ascending?: boolean }) => Promise<{ data: Discount[] | null; error: { message: string } | null }> } } } }
const input = "rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm";
export default async function PromotionsPage() {
  const context = await requireAdminContext(); const supabase = await createClient(); const commercial = supabase as unknown as CommercialClient;
  const [productsResult, branchesResult, discountsResult] = await Promise.all([supabase.from("products").select("id, name, unit_type, active").eq("organization_id", context.organizationId).order("name"), supabase.from("branches").select("id, name").eq("organization_id", context.organizationId).eq("active", true).order("name"), commercial.from("product_weight_discounts").select("id, product_id, branch_id, minimum_grams, discount_type, discount_value, active, valid_from, valid_until").eq("organization_id", context.organizationId).order("valid_from", { ascending: false })]);
  const error = [productsResult.error, branchesResult.error, discountsResult.error].find(Boolean); const products = productsResult.data ?? []; const branches = branchesResult.data ?? []; const productNames = new Map(products.map((product) => [product.id, product.name])); const branchNames = new Map(branches.map((branch) => [branch.id, branch.name]));
  return <main className="mx-auto max-w-6xl p-5 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-stone-500">Inicio / Promociones</p><h1 className="mt-1 text-3xl font-black tracking-tight">Promociones</h1><p className="mt-2 text-stone-600">Descuentos por peso vigentes y programados.</p></div><Modal title="Nueva promoción" trigger="+ Nueva promoción"><form action={saveWeightDiscountAction} className="grid gap-3"><select className={input} name="product_id" required><option value="">Producto</option>{products.filter((product) => product.active && product.unit_type === "WEIGHT").map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select><select className={input} name="branch_id"><option value="">Todas las sucursales</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><div className="grid gap-3 sm:grid-cols-3"><input className={input} min="0.001" name="minimum_kg" placeholder="Desde kg" required step="0.001" type="number" /><select className={input} name="discount_type"><option value="PERCENTAGE">Porcentaje</option><option value="FIXED_PRICE_PER_KG">Precio por kg</option></select><input className={input} min="0.01" name="discount_value" placeholder="Valor" required step="0.01" type="number" /></div><input name="active" type="hidden" value="on" /><input name="valid_from" type="hidden" value="" /><input name="valid_until" type="hidden" value="" /><button className="justify-self-start rounded-lg bg-rose-800 px-4 py-2 text-sm font-bold text-white">Guardar promoción</button></form></Modal></div>{error ? <p className="mt-5 rounded-lg bg-red-50 p-4 text-red-800">{error.message}</p> : null}
    <section className="mt-7 divide-y rounded-xl bg-white shadow-sm">{(discountsResult.data ?? []).map((discount) => <article className="flex flex-wrap items-center justify-between gap-4 p-4" key={discount.id}><div><h2 className="font-bold">{productNames.get(discount.product_id)}</h2><p className="mt-1 text-sm text-stone-600">{discount.discount_type === "PERCENTAGE" ? `${(discount.discount_value / 100).toLocaleString("es-AR")}%` : `$${(discount.discount_value / 100).toLocaleString("es-AR")}/kg`} desde {(discount.minimum_grams / 1000).toLocaleString("es-AR")} kg · {discount.branch_id ? branchNames.get(discount.branch_id) : "Todas las sucursales"}</p></div><StatusBadge tone={discount.active ? "success" : "neutral"}>{discount.active ? "Activa" : "Inactiva"}</StatusBadge></article>)}{!discountsResult.data?.length ? <p className="p-8 text-center text-stone-500">Todavía no hay promociones.</p> : null}</section>
  </main>;
}
