import { formatCurrency, formatWeight } from "@carnicerias/business-logic";
import Link from "next/link";
import { notFound } from "next/navigation";

import { MetricCard, SectionHeader, StatusBadge } from "../../../../components/admin-ui";
import { requireAdminContext } from "../../../../lib/admin";
import { localDayStart, stockPriority } from "../../../../lib/multibranch";
import { createClient } from "../../../../lib/supabase/server";

type Tab = "summary" | "stock" | "sales" | "operation";
interface DashboardData { periods: { today: { grossCents: number; previousGrossCents: number; salesCount: number; averageTicketCents: number; kilograms: number } }; paymentsThisMonth: { method: string; amountCents: number }[] }
const paymentLabels: Record<string, string> = { CASH: "Efectivo", TRANSFER: "Transferencia", DEBIT: "Débito", CREDIT: "Crédito", OTHER: "Otro" };

export default async function BranchPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const context = await requireAdminContext();
  const requestedTab = typeof query.tab === "string" ? query.tab : "";
  const tab: Tab = ["stock", "sales", "operation"].includes(requestedTab) ? requestedTab as Tab : "summary";
  const stockSearch = typeof query.q === "string" ? query.q.trim().toLocaleLowerCase("es") : "";
  const supabase = await createClient();
  const [branchResult, dashboardResult, stockResult, weekSalesResult, recentSalesResult, restocksResult, wasteResult] = await Promise.all([
    supabase.from("branches").select("id, name, code, address, active").eq("organization_id", context.organizationId).eq("id", id).maybeSingle(),
    supabase.rpc("get_admin_dashboard", { p_branch_id: id }),
    supabase.from("branch_stock_status").select("product_id, product_name, current_stock_grams, minimum_stock_grams, target_stock_grams, suggested_replenishment_grams, stock_status").eq("organization_id", context.organizationId).eq("branch_id", id),
    supabase.from("sales").select("id, completed_at").eq("organization_id", context.organizationId).eq("branch_id", id).eq("status", "COMPLETED").gte("completed_at", localDayStart(context.timezone, 6)),
    supabase.from("sales").select("id, total_cents, total_weight_grams, completed_at, created_at").eq("organization_id", context.organizationId).eq("branch_id", id).eq("status", "COMPLETED").order("completed_at", { ascending: false }).limit(6),
    supabase.from("stock_movements").select("product_id, type, quantity_grams, occurred_at").eq("organization_id", context.organizationId).eq("branch_id", id).in("type", ["PURCHASE", "RETURN", "ADJUSTMENT_POSITIVE", "TRANSFER_IN"]).order("occurred_at", { ascending: false }).limit(6),
    supabase.from("stock_operations").select("id, waste_reason, occurred_at").eq("organization_id", context.organizationId).eq("branch_id", id).eq("operation_type", "WASTE").order("occurred_at", { ascending: false }).limit(6)
  ]);
  if (!branchResult.data) notFound();
  const error = [branchResult.error, dashboardResult.error, stockResult.error, weekSalesResult.error, recentSalesResult.error, restocksResult.error, wasteResult.error].find(Boolean);
  if (error) return <main className="mx-auto max-w-7xl p-8 text-red-800">No se pudo cargar la sucursal: {error.message}</main>;
  const saleIds = (weekSalesResult.data ?? []).map((sale) => sale.id);
  const itemsResult = saleIds.length ? await supabase.from("sale_items").select("sale_id, product_id, product_name_snapshot, weight_grams, subtotal_cents, discount_cents").in("sale_id", saleIds) : { data: [], error: null };
  if (itemsResult.error) return <main className="mx-auto max-w-7xl p-8 text-red-800">No se pudo cargar el detalle comercial: {itemsResult.error.message}</main>;

  const dashboard = dashboardResult.data as unknown as DashboardData;
  const today = dashboard.periods.today;
  const stock = (stockResult.data ?? []).map((row) => { const current = row.current_stock_grams ?? 0; const minimum = row.minimum_stock_grams ?? 0; return { ...row, current, minimum, target: row.target_stock_grams ?? 0, suggested: row.suggested_replenishment_grams ?? 0, priority: stockPriority(row.stock_status, current, minimum) }; }).sort((a, b) => a.priority.rank - b.priority.rank || a.current - b.current || (a.product_name ?? "").localeCompare(b.product_name ?? "", "es"));
  const visibleStock = stock.filter((row) => !stockSearch || (row.product_name ?? "").toLocaleLowerCase("es").includes(stockSearch));
  const stockByProduct = new Map(stock.map((row) => [row.product_id, row]));
  const urgent = stock.filter((row) => row.priority.rank < 2);
  const normalStock = stock.filter((row) => row.priority.rank === 2).length;
  const items = itemsResult.data as unknown as { sale_id: string; product_id: string; product_name_snapshot: string; weight_grams: number; subtotal_cents: number; discount_cents: number }[];
  const productTotals = new Map<string, { name: string; grams: number; cents: number }>();
  for (const item of items) { const total = productTotals.get(item.product_id) ?? { name: item.product_name_snapshot, grams: 0, cents: 0 }; total.grams += item.weight_grams; total.cents += item.subtotal_cents; productTotals.set(item.product_id, total); }
  const topProducts = [...productTotals.values()].sort((a, b) => b.cents - a.cents).slice(0, 5);
  const todaySales = new Set((weekSalesResult.data ?? []).filter((sale) => (sale.completed_at ?? "") >= localDayStart(context.timezone)).map((sale) => sale.id));
  const todayDiscounts = items.filter((item) => todaySales.has(item.sale_id)).reduce((sum, item) => sum + item.discount_cents, 0);
  const restocks = (restocksResult.data ?? []).map((movement) => ({ ...movement, productName: stockByProduct.get(movement.product_id)?.product_name ?? "Producto" }));
  const recentSales = recentSalesResult.data ?? [];
  const recentWaste = wasteResult.data ?? [];
  const change = today.previousGrossCents ? ((today.grossCents - today.previousGrossCents) / today.previousGrossCents) * 100 : null;
  const tabLink = (next: Tab) => `/admin/branches/${id}${next === "summary" ? "" : `?tab=${next}`}`;
  const tabs: [Tab, string][] = [["summary", "Resumen"], ["stock", "Stock"], ["sales", "Ventas"], ["operation", "Operación"]];
  const adminLinks: [string, string][] = [["Stock y movimientos", "/admin/stock"], ["Productos, precios y descuentos", "/admin/catalog"], ["Avisos", "/admin/catalog#announcements"], ["Empleados", "/admin/employees"], ["Dispositivos", "/admin/devices"], ["Auditoría", "/admin/audit"]];

  return <main className="mx-auto max-w-7xl p-5 sm:p-10"><Link className="text-sm font-bold text-rose-800 hover:underline" href="/admin">← Volver a sucursales</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-bold uppercase tracking-wider text-rose-800">Sucursal</p><h1 className="mt-1 text-3xl font-black">{branchResult.data.name}</h1><p className="mt-1 text-stone-600">{branchResult.data.code}{branchResult.data.address ? ` · ${branchResult.data.address}` : ""}</p></div><StatusBadge tone={branchResult.data.active ? "success" : "neutral"}>{branchResult.data.active ? "ACTIVA" : "INACTIVA"}</StatusBadge></div>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="Ventas hoy" value={formatCurrency(BigInt(today.grossCents))} /><MetricCard label="Kg vendidos" value={formatWeight(Math.round(today.kilograms * 1000))} /><MetricCard label="Tickets" value={String(today.salesCount)} /><MetricCard label="Ticket promedio" value={formatCurrency(BigInt(today.averageTicketCents))} /></section>
    <nav className="mt-7 flex gap-1 border-b border-stone-300" aria-label="Secciones de sucursal">{tabs.map(([key, label]) => <Link className={`border-b-2 px-4 py-3 text-sm font-bold ${tab === key ? "border-rose-800 text-rose-800" : "border-transparent text-stone-600 hover:text-stone-950"}`} href={tabLink(key)} key={key}>{label}</Link>)}</nav>
    {tab === "summary" ? <div className="mt-6 grid gap-7 lg:grid-cols-[1.1fr_.9fr]"><section><SectionHeader title="Requiere atención" action={<Link className="text-sm font-bold text-rose-800 hover:underline" href={`/admin/attention?branch=${id}`}>Ver todo →</Link>} /><div className="mt-3 divide-y rounded-xl border bg-white">{urgent.slice(0, 5).map((row) => <div className="flex items-center justify-between gap-3 px-4 py-3" key={row.product_id}><div><strong>{row.product_name}</strong><p className="text-sm text-stone-600">Actual {formatWeight(row.current)} · Reponer {formatWeight(row.suggested)}</p></div><StatusBadge tone={row.priority.rank === 0 ? "critical" : "warning"}>{row.priority.label}</StatusBadge></div>)}{!urgent.length ? <p className="px-4 py-5 text-emerald-700">Sin alertas de stock.</p> : null}</div>{change !== null ? <p className={`mt-4 text-sm font-bold ${change < 0 ? "text-red-700" : "text-emerald-700"}`}>{change >= 0 ? "+" : ""}{change.toFixed(1)}% de ventas frente a ayer.</p> : null}</section><section><SectionHeader title="Resumen de stock" action={<Link className="text-sm font-bold text-rose-800 hover:underline" href={tabLink("stock")}>Ver stock →</Link>} /><dl className="mt-3 grid grid-cols-3 gap-3"><MetricCard label="Agotados" value={String(stock.filter((row) => row.priority.rank === 0).length)} /><MetricCard label="Bajo mínimo" value={String(stock.filter((row) => row.priority.rank === 1).length)} /><MetricCard label="Normal" value={String(normalStock)} /></dl><SectionHeader title="Productos más vendidos" description="Últimos 7 días" /><div className="mt-3 divide-y rounded-xl border bg-white">{topProducts.slice(0, 4).map((product) => <div className="flex justify-between gap-3 px-4 py-3" key={product.name}><span className="font-bold">{product.name}</span><span>{formatWeight(product.grams)} · <strong>{formatCurrency(BigInt(product.cents))}</strong></span></div>)}{!topProducts.length ? <p className="px-4 py-5 text-stone-500">Sin ventas recientes.</p> : null}</div></section></div> : null}
    {tab === "stock" ? <section className="mt-6"><SectionHeader title="Stock de la sucursal" description="Ordenado por urgencia." /><form className="mt-4 flex max-w-md gap-2"><input className="min-w-0 flex-1 rounded-lg border border-stone-300 px-3 py-2" defaultValue={typeof query.q === "string" ? query.q : ""} name="q" placeholder="Buscar producto…" /><input name="tab" type="hidden" value="stock" /><button className="rounded-lg border px-4 py-2 font-bold">Buscar</button></form><div className="mt-4 overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b bg-stone-50 text-stone-500"><tr><th className="p-3">Producto</th><th className="p-3">Actual</th><th className="p-3">Mínimo</th><th className="p-3">Objetivo</th><th className="p-3">Cobertura</th><th className="p-3">Reponer</th><th className="p-3">Estado</th></tr></thead><tbody>{visibleStock.map((row) => { const daily = (productTotals.get(row.product_id ?? "")?.grams ?? 0) / 7; return <tr className="border-b border-stone-100" key={row.product_id}><td className="p-3 font-bold">{row.product_name}</td><td className="p-3">{formatWeight(row.current)}</td><td className="p-3">{formatWeight(row.minimum)}</td><td className="p-3">{formatWeight(row.target)}</td><td className="p-3">{daily > 0 ? `≈ ${(row.current / daily).toFixed(1)} días` : "Sin ventas recientes"}</td><td className="p-3">{formatWeight(row.suggested)}</td><td className="p-3"><StatusBadge tone={row.priority.rank === 0 ? "critical" : row.priority.rank === 1 ? "warning" : row.priority.rank === 2 ? "success" : "neutral"}>{row.priority.label}</StatusBadge></td></tr>; })}</tbody></table></div>{!visibleStock.length ? <p className="mt-4 text-stone-500">No hay productos para esta búsqueda.</p> : null}</section> : null}
    {tab === "sales" ? <div className="mt-6 grid gap-7 lg:grid-cols-2"><section><SectionHeader title="Ventas recientes" action={<Link className="text-sm font-bold text-rose-800 hover:underline" href={`/admin/sales?preset=today&branch=${id}`}>Ver ventas →</Link>} /><div className="mt-3 divide-y rounded-xl border bg-white">{recentSales.map((sale) => <div className="flex justify-between gap-4 px-4 py-3 text-sm" key={sale.id}><span>{new Date(sale.completed_at ?? sale.created_at).toLocaleString("es-AR", { timeZone: context.timezone })}</span><strong>{formatCurrency(BigInt(sale.total_cents))} · {formatWeight(sale.total_weight_grams)}</strong></div>)}{!recentSales.length ? <p className="px-4 py-5 text-stone-500">Sin ventas recientes.</p> : null}</div><SectionHeader title="Productos vendidos" description="Últimos 7 días" /><div className="mt-3 divide-y rounded-xl border bg-white">{topProducts.map((product) => <div className="flex justify-between gap-3 px-4 py-3" key={product.name}><strong>{product.name}</strong><span>{formatWeight(product.grams)} · {formatCurrency(BigInt(product.cents))}</span></div>)}</div></section><section><SectionHeader title="Métricas comerciales" /><div className="mt-3 grid gap-3 sm:grid-cols-2"><MetricCard label="Descuentos hoy" value={formatCurrency(BigInt(todayDiscounts))} /><MetricCard label="Facturación hoy" value={formatCurrency(BigInt(today.grossCents))} /></div><SectionHeader title="Medios de pago" description="Mes actual" /><div className="mt-3 divide-y rounded-xl border bg-white">{dashboard.paymentsThisMonth.map((payment) => <div className="flex justify-between px-4 py-3" key={payment.method}><span>{paymentLabels[payment.method] ?? payment.method}</span><strong>{formatCurrency(BigInt(payment.amountCents))}</strong></div>)}</div></section></div> : null}
    {tab === "operation" ? <div className="mt-6 grid gap-7 lg:grid-cols-2"><section><SectionHeader title="Mermas recientes" action={<Link className="text-sm font-bold text-rose-800 hover:underline" href="/admin/stock">Ver movimientos →</Link>} /><div className="mt-3 divide-y rounded-xl border bg-white">{recentWaste.map((waste) => <div className="flex justify-between gap-3 px-4 py-3 text-sm" key={waste.id}><span>{new Date(waste.occurred_at).toLocaleString("es-AR", { timeZone: context.timezone })}</span><strong>{waste.waste_reason ?? "Merma"}</strong></div>)}{!recentWaste.length ? <p className="px-4 py-5 text-stone-500">Sin mermas recientes.</p> : null}</div><SectionHeader title="Reingresos recientes" /><div className="mt-3 divide-y rounded-xl border bg-white">{restocks.map((movement) => <div className="flex justify-between gap-3 px-4 py-3 text-sm" key={`${movement.product_id}-${movement.occurred_at}`}><span>{movement.productName} · {movement.type}</span><strong>+{formatWeight(Math.abs(movement.quantity_grams))}</strong></div>)}{!restocks.length ? <p className="px-4 py-5 text-stone-500">Sin reingresos recientes.</p> : null}</div></section><section><SectionHeader title="Administración de la sucursal" description="Accesos a las funciones existentes." /><div className="mt-3 grid gap-2 sm:grid-cols-2">{adminLinks.map(([label, href]) => <Link className="rounded-lg border bg-white px-4 py-3 font-bold hover:border-rose-300 hover:text-rose-800" href={href} key={label}>{label} →</Link>)}</div></section></div> : null}
  </main>;
}
